version: "2"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    command: mongod --port 27017 --bind_ip_all
    ports:
      - '27017:27017'
  server:
    restart: always
    build:
      context: ./hox-server
    environment:
      DATABASE: mongodb:27017
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_AUTH: admin
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
  client:
    build:
      context: ./hox-client
    ports:
      - '4200:4200'
    depends_on:
      - server
